### ISSUE TITLE
When do pcu.read_ply the jupyter notebook kernel dies, 

### ISSUE THREAD

**Issue by JMParker-KR** [fwilliams/point-cloud-utils#11]
I am Using
Window10
python 3.6
and just did conda install -c conda-forge point_cloud_utils on a new anconda env

**Comment by fwilliams** [comment]
Can you upload your PLY file. What version of `point_cloud_utils` are you using?

**Comment by JMParker-KR** [comment]
> Can you upload your PLY file. What version of `point_cloud_utils` are you using?

Thank you for your reply
I fixed it by using OFF file instead , I think the problem was the ply file was in binary  or it had not enough information in the ply file

[stool_0001.zip](https://github.com/fwilliams/point-cloud-utils/files/3993736/stool_0001.zip)

**Comment by fwilliams** [comment]
Binary PLY files should work. It might have been an issue with the file itself. Ideally, the function shouldn't crash on bad inputs though.

**Comment by fwilliams** [comment]
This is fixed with the new mesh IO API:
* [Documentation for loading meshes and point clouds](https://github.com/fwilliams/point-cloud-utils#loading-meshes-and-point-clouds)
* [Documentation for saving meshes and point clouds](https://github.com/fwilliams/point-cloud-utils#saving-meshes-and-point-clouds)
