### ISSUE TITLE
program end with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by bearinsuke** [fwilliams/point-cloud-utils#15]
Hi
I use pcu for sampling a ply file. It shows Process finished with exit code -1073741819 (0xC0000005) in the middle. But there is no such thing when I debug it. 
Python version 3.7.6
Win10

**Comment by fwilliams** [comment]
Hi, thanks for reporting this issue. 

Could you provide a small code sample that reproduces the crash as well as the exact data you used?

**Comment by bearinsuke** [comment]
Sure
[code.txt](https://github.com/fwilliams/point-cloud-utils/files/4210972/code.txt)

**Comment by fwilliams** [comment]
Can you also provide the meshes
```
    a = "OnlineX_190_240/Scan_2.ply"
    b = "OnlineX_190_240/Trail.ply"
```

The crash is probably due to a problem in the data.

**Comment by bearinsuke** [comment]
How can I provide it? I didn't meet such an error when using other API.....

**Comment by fwilliams** [comment]
Upload it to some file share site (e.g. Google Drive) and post a link. 

Another library might handle your input data differently. The code example you posted works with data I have on my machine. I can't fix the problem if you don't give me exact code to reproduce your issue.

**Comment by bearinsuke** [comment]
Ok, actually, I installed all these libraries from conda including open3d. 
The link can proceed these 3d files is 
https://drive.google.com/drive/folders/1Ks2g7lB7DjA9YJCBlrXkSBr1iXQTKaLV?usp=sharing
Thank you

**Comment by bearinsuke** [comment]
> Ok, actually, I installed all these libraries from conda including open3d.
> The link can proceed these 3d files is
> https://drive.google.com/drive/folders/1Ks2g7lB7DjA9YJCBlrXkSBr1iXQTKaLV?usp=sharing
> Thank you
Actually, the problem happens when I trying to read it with pcu, and sometimes the program will work.

**Comment by fwilliams** [comment]
Thanks for posting that. 

Here's the output I get on that data:
```python
In [6]: v_t, f_t, n_t, _ = pcu.read_ply("Scan_2.ply")                                                                          
Warning:  Can't find property 'vertex_indices' in element 'face'
[1]    11585 segmentation fault (core dumped)  ipython
```
So it looks like the PLY loader is crashing because your `Scan_2.ply` is missing is a bit weird. Right now, point-cloud-utils is using the PLY reader in LibIGL under the hood which is pretty brittle. I plan to rewrite all the loading code to use a different mesh IO library that's more robust to slightly malformed inputs but likely won't have time to do this for a while. 

In the meantime, you can either 
1. use a different library to load the PLY (look at [pymesh](https://github.com/PyMesh/PyMesh) or [python-plyfile](https://github.com/dranjan/python-plyfile) or 
2. fix the mesh with [MeshLab](http://www.meshlab.net/) (Open the mesh with meshlab then click File -> Export Mesh then make sure you select the checkbox with Normal).

**Comment by bearinsuke** [comment]
Thanks for your answer.
