### ISSUE TITLE
Math behind the Sinkhorn implementation

### ISSUE THREAD

**Issue by philippwulff** [fwilliams/point-cloud-utils#70]
Hi, 

thanks for providing this code. I was looking into the implementation of the [Sinkhorn algorithm in point-cloud-utils](https://github.com/fwilliams/point-cloud-utils/blob/master/point_cloud_utils/_sinkhorn.py), but I do not understand what is going on. It does not match the equation 4.15 in [this paper](https://arxiv.org/pdf/1803.00567.pdf):

![Screenshot 2023-08-15 at 19 16 43](https://github.com/fwilliams/point-cloud-utils/assets/45896065/feaa1d57-b507-462b-9330-cfb858e5d257)

Is it there a paper reference for this specific implementation or could someone please point me towards a resource that explains the Sinkhorn iterations implemented here?

Thanks!

**Comment by philippwulff** [comment]
I found these two equations on page 78 of the paper I shared. They are close to what is implemented in the code. But it is not identical ...

![Screenshot 2023-08-15 at 20 47 34](https://github.com/fwilliams/point-cloud-utils/assets/45896065/0837156c-4eaa-4ce0-9282-58975602109e)

**Comment by fwilliams** [comment]
Hi, 

It's been a few years since I wrote this so I don't remember all the details.

As you said, the main reason for this implementation is that things are more numerically stable in the log domain. 

I think the naive sinkhorn algorithm defines an entropy regularization parameter $\alpha$. I think `eps` is the reciprocal of this parameter (possibly with other constants bundled in).

**Comment by philippwulff** [comment]
Thanks for the answer. I think that `eps` is the regularization parameter directly. I coded up the naive Sinkhorn algorithm [here](https://philippwulff.github.io/#/blog/shape-reconstruction-metrics-in-3d) in case anyone is interested :)
